---
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: woker-pod
    app: voting-demo-app
spec:
  containers:
    - name: worker
      image: dockersamples/examplevotingapp_worker
...